---
sudo: required
language: generic
services: docker
dist: xenial
addons:
  apt:
    packages:
      - libssl1.0.0

before_script:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.8 python3.8-dev python3.8-distutils
  - sudo pip install tox
  - sudo -E docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - (cd .. && git clone https://github.com/estesp/manifest-tool)
  - (cd ../manifest-tool && git checkout v0.9.0)
  - (cd ../manifest-tool && sudo -E make && sudo -E make install)

jobs:
  include:
    - stage: run unit tests
      script: tox
    - stage: build functest-kubernetes-core image
      script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - amd64_dirs="docker/core"
        - arm64_dirs=""
    - stage: publish functest-kubernetes-core manifests
      script: >
        sudo manifest-tool push from-args \
          --platforms linux/amd64 \
          --template ${DOCKER_USERNAME}/functest-kubernetes-core:ARCH-kali \
          --target ${DOCKER_USERNAME}/functest-kubernetes-core:kali
    - stage: build functest-kubernetes-[healthcheck,cnf,security] images
      script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - amd64_dirs="docker/healthcheck"
        - arm64_dirs=""
    - script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - amd64_dirs="docker/cnf"
        - arm64_dirs=""
        - arm_dirs=""
    - script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - amd64_dirs="docker/security"
        - arm64_dirs=""
        - arm_dirs=""
    - stage: publish functest-kubernetes-[healthcheck,cnf,security] manifests
      script: >
        sudo manifest-tool push from-args \
          --platforms linux/amd64 \
          --template \
          ${DOCKER_USERNAME}/functest-kubernetes-healthcheck:ARCH-kali \
          --target ${DOCKER_USERNAME}/functest-kubernetes-healthcheck:kali
    - script: >
        sudo manifest-tool push from-args \
          --platforms linux/amd64 \
          --template ${DOCKER_USERNAME}/functest-kubernetes-cnf:ARCH-kali \
          --target ${DOCKER_USERNAME}/functest-kubernetes-cnf:kali
    - script: >
        sudo manifest-tool push from-args \
          --platforms linux/amd64 \
          --template \
            ${DOCKER_USERNAME}/functest-kubernetes-security:ARCH-kali \
          --target ${DOCKER_USERNAME}/functest-kubernetes-security:kali
    - stage: build functest-kubernetes-smoke image
      script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - amd64_dirs="docker/smoke"
        - arm64_dirs=""
    - stage: publish functest-kubernetes-smoke manifests
      script: >
        sudo manifest-tool push from-args \
          --platforms linux/amd64 \
          --template ${DOCKER_USERNAME}/functest-kubernetes-smoke:ARCH-kali \
          --target ${DOCKER_USERNAME}/functest-kubernetes-smoke:kali
