---
- hosts: 127.0.0.1
  roles:
    - role: collivier.xtesting
      project: functest-kubernetes
      db_project: functest
      gerrit_project: functest-kubernetes
      builds:
        dependencies:
          - repo: _
            dport:
            container: golang
            tag: 1.14-alpine3.12
        steps:
          - name: build opnfv/functest-kubernetes-core
            containers:
              - name: functest-kubernetes-core
                ref_arg: BRANCH
                path: docker/core
          - name: build opnfv/functest-kubernetes-healthcheck
            containers:
              - name: functest-kubernetes-healthcheck
                ref_arg:
                path: docker/healthcheck
              - name: functest-kubernetes-cnf
                ref_arg: BRANCH
                path: docker/cnf
              - name: functest-kubernetes-security
                ref_arg: BRANCH
                path: docker/security
          - name: build containers
            containers:
              - name: functest-kubernetes-smoke
                ref_arg:
                path: docker/smoke
      suites:
        - container: functest-kubernetes-healthcheck
          tests:
            - k8s_smoke
        - container: functest-kubernetes-smoke
          tests:
            - xrally_kubernetes
            - k8s_conformance
        - container: functest-kubernetes-security
          tests:
            - kube_hunter
            - kube_bench
        - container: functest-kubernetes-cnf
          tests:
            - k8s_vims
